#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#include <stdint.h>

#define LED_1_GREEN     6  
#define LED_2_RED       8
#define LED_2_GREEN     41 
#define LED_2_BLUE      12
#define BUTTON_PIN      38

#define DEVICE_ID       7205
#define DEFAULT_HUE_PERCENT  (DEVICE_ID % 100)
#define PWM_TOP_VALUE   1000

#define DOUBLE_CLICK_TIMEOUT_MS  400
#define DEBOUNCE_MS              50
#define MODE_BLINK_SLOW_MS       1000
#define MODE_BLINK_FAST_MS       200
#define VALUE_CHANGE_INTERVAL_MS 50

typedef enum {
    MODE_NO_INPUT = 0,
    MODE_HUE,
    MODE_SATURATION,
    MODE_BRIGHTNESS
} input_mode_t;

typedef struct {
    uint16_t h;
    uint8_t s;
    uint8_t v;
} hsv_color_t;

#define NRFX_CLOCK_ENABLED 1
#define CLOCK_ENABLED 1
#define NRFX_CLOCK_CONFIG_LF_SRC 0
#define NRFX_CLOCK_CONFIG_IRQ_PRIORITY 6
#define CLOCK_CONFIG_IRQ_PRIORITY 6

#define NRFX_POWER_ENABLED 1
#define POWER_ENABLED 1
#define NRFX_POWER_CONFIG_IRQ_PRIORITY 6
#define POWER_CONFIG_IRQ_PRIORITY 6

#define NRFX_GPIOTE_ENABLED 1
#define GPIOTE_ENABLED 1
#define NRFX_GPIOTE_CONFIG_NUM_OF_LOW_POWER_EVENTS 4
#define NRFX_GPIOTE_CONFIG_IRQ_PRIORITY 6

#define NRFX_PWM_ENABLED 1
#define NRFX_PWM0_ENABLED 1
#define NRFX_PWM1_ENABLED 1
#define PWM_ENABLED 1
#define PWM0_ENABLED 1
#define PWM1_ENABLED 1
#define NRFX_PWM_DEFAULT_CONFIG_IRQ_PRIORITY 6

#define NRFX_PWM_DEFAULT_CONFIG_OUT0_PIN 31
#define NRFX_PWM_DEFAULT_CONFIG_OUT1_PIN 31
#define NRFX_PWM_DEFAULT_CONFIG_OUT2_PIN 31
#define NRFX_PWM_DEFAULT_CONFIG_OUT3_PIN 31
#define NRFX_PWM_DEFAULT_CONFIG_BASE_CLOCK 4
#define NRFX_PWM_DEFAULT_CONFIG_COUNT_MODE 0
#define NRFX_PWM_DEFAULT_CONFIG_TOP_VALUE 1000
#define NRFX_PWM_DEFAULT_CONFIG_LOAD_MODE 0
#define NRFX_PWM_DEFAULT_CONFIG_STEP_MODE 0

#define NRFX_NVMC_ENABLED 1

#endif